### ISSUE TITLE
Credentials required on cli version but not api version

### ISSUE THREAD

**Issue by kyle-mccarthy** [ovhemert/pino-stackdriver#46]
## 🐛 Bug Report

I am not sure if this is intentional, but it looks like the CLI version requires credentials while the API version does not.

I am deploying to a cloud run instance and the service account associated with the instance has the necessary permissions to write logs.

## To Reproduce

Run CLI without passing credentials or having ENV var set.

## Expected behavior

Use CLI without specifying credentials.

## Your Environment

- GCP Cloud Run
- Service account has log writer permissions

**Comment by ovhemert** [comment]
Can you point me to the difference between the CLI and API that you refer to?
Because also the API required credentials, and if they are not specified, it falls back to env var `GOOGLE_APPLICATION_CREDENTIALS`.

**Comment by ovhemert** [comment]
For the CLI it is also optional to pass in the credentials on the command-line. In that case, the ENV setting is still required. If both are missing, an error will be thrown. This is how it's intended to work and the scenario can be tested with [this test](https://github.com/ovhemert/pino-stackdriver/blob/master/test/cli.test.js#L50-L61). Please run `npm run test` to see if that validates.

If it's possible in your environment that also the ENV setting is not needed, and you should be able to log without passing in any credentials, maybe we can adjust the package to support this.

Under the hood, I'm using [@google-cloud/logging](https://www.npmjs.com/package/@google-cloud/logging). So if it's supported there, we can make that happen.

**Comment by kyle-mccarthy** [comment]
I agree that the CLI treats them as optional to explicitly require them, but it implicitly requires credentials by throwing an error if neither the credential arg is set nor the ENV variable. [This test](https://github.com/ovhemert/pino-stackdriver/blob/master/test/stackdriver.test.js#L149) for the stackdriver asserts that 'works without passing credentials'.

This led me to believe that the API already works without explicitly providing credentials as a parameter and also without the ENV variable. I very well may be mistaken.

I will try to checkout @google-cloud/logging to see if it supported, and if so what changes would need to be made. Thanks!

**Comment by ovhemert** [comment]
I ran some tests with the CLI on GCE, and it seems that it will work without specifying the credentials. The thing is, that initially this package was created to be able to add logs to stackdriver from a remote location (so credentials always required).

I've made the credentials optional now, so it will not throw an error anymore if they are missing

Thanks for the input 👍🏻

**Comment by kyle-mccarthy** [comment]
This is awesome, thank you for looking into this!
