### ISSUE TITLE
Logs not showing inside GKE

### ISSUE THREAD

**Issue by klaaz0r** [ovhemert/pino-stackdriver#58]
## 🐛 Bug Report

I have everything setup correctly, secret with credentials etc. No errors are thrown but the actual logs are not showing up inside the stackdriver logging for my kubernetes containers

## To Reproduce

```js
pinoms({
    streams: [
      {
        stream: stackdriver.createWriteStream({
          logName: "NAME",
          projectId: "PROJECT_ID"
        })
      }
    ]
  });
```

## Expected behavior
I want the logs to show up inside the actual container logs/kubernetes. Can this be a problem with missing labels? 

## Your Environment

- Google Cloud Kubernetes Engine

**Comment by klaaz0r** [comment]
I did some digging: 

https://github.com/googleapis/nodejs-logging/blob/6f01c6679d7b4689ceb03011f37e4def5d9025f4/src/log.ts#L822

It looks like `@google-cloud/logging` by itself fetches the right labels if non are provided. But `pino-stackdriver` set's a default:

```js
  const entry = {
    meta: {
      resource: resource || { type: 'global' },
      severity
    },
    data
  }
``` 

found here: https://github.com/ovhemert/pino-stackdriver/blob/6bbb026f242a98fc80b81b2492f00e2c29c8192b/src/stackdriver.js#L45

Should this module default to  `{ type: 'global' }` or leave it to `@google-cloud/logging`? I am happy to create a PR

**Comment by ovhemert** [comment]
Is that only an issue you have with the `resource.labels`? Because if you do not provide anything to the module, it defaults to a resource of `{ type: 'global' }`. But in that case `resource.labels` is still undefined. It only sets `type`.
