### ISSUE TITLE
Can't add param "logName" from CLI

### ISSUE THREAD

**Issue by meotimdihia** [ovhemert/pino-stackdriver#63]
https://github.com/ovhemert/pino-stackdriver/blob/master/src/cli.js
It looks like CLI support only "project" and "credentials"

**Comment by ovhemert** [comment]
Good catch! Would you mind to send a PR that adds this to `cli.js`?

**Comment by meotimdihia** [comment]
Sorry, I forgot about this. @Boelensman1 pull requests to fix the problem. LogName is important, Google Logs Viewer is using it: 

![msedge_2020-05-29_10-54-22](https://user-images.githubusercontent.com/300961/83219658-1b679f00-a19b-11ea-99c1-97bae3629d5e.png)
