### ISSUE TITLE
 TypeError: log[chunk.meta.severity] is not a function

### ISSUE THREAD

**Issue by Mistic92** [ovhemert/pino-stackdriver#66]
## 🐛 Bug Report
My app can't start because of type error. I'm using it with nestjs[ pino logger](https://github.com/iamolegga/nestjs-pino)

## To Reproduce

Paste your code here:

```js
    LoggerModule.forRoot({
      pinoHttp: [
        {
          name: 'add some name to every JSON line',
          level: 'debug',
          prettyPrint: false,
          useLevelLabels: true,
          // and all the others...
        },
        stackdriver.createWriteStream({
          logName: 'pino-nest',
          projectId: 'yosh-bot-gateway',
        }),
      ],
    }),
```

## Expected behavior

Just work :) 

Paste the results here:

```js
(node:28720) UnhandledPromiseRejectionWarning: TypeError: log[chunk.meta.severity] is not a function
    at Writable.write [as _write] (C:\Projects\bot-gateway\node_modules\pino-stackdriver\src\stackdriver.js:84:31)
    at doWrite (_stream_writable.js:415:12)
```

## Your Environment

- *os*: Windows

**Comment by ovhemert** [comment]
Can you paste an example of the log messages that you have on startup. 
The reason  could be that the properties `msg`, `message` or `level` are all missing or some invalid.
