### ISSUE TITLE
Support for credentials object parameter

### ISSUE THREAD

**Issue by frandiox** [ovhemert/pino-stackdriver#68]
## 🚀 Feature Proposal

Support passing credentials object parameter to Stackdriver lib instead of specifying a key file path.

## Motivation

Every GCP Node package, including Stackdriver, allows passing credentials in several ways:

- `process.env.GOOGLE_APPLICATION_CREDENTIALS` with the path to they key file.
- Passing option `{ keyFilename: '...' }` with the path to they key file.
- Passing option `{ credentials: { client_email: '...', private_key: '...' } }` without any key file in disk.

Only the first way is supported in this library but the other ones come handy in some situations.

## Example

https://github.com/googleapis/google-auth-library-nodejs/blob/master/samples/credentials.js#L36

https://github.com/googleapis/nodejs-logging/blob/master/src/index.ts#L206

## Other

I think this is not hard to implement with backward support by just assigning the current `credentials` parameter to `process.env.GOOGLE_APPLICATION_CREDENTIALS` if `typeof credentials === 'string'`, or passing the whole thing to `Logging` constructor otherwise (and updating the `.d.ts` file).

**Comment by ovhemert** [comment]
Can you send a PR for the proposed additions? Sounds like a plan to me. 👍

**Comment by jhonny111s** [comment]
Hello i did a pull request related to this enhancement, could someone review it
