### ISSUE TITLE
Prefix and labels options not working

### ISSUE THREAD

**Issue by frandiox** [ovhemert/pino-stackdriver#69]
## 🐛 Bug Report

`toLogEntry` is expecting `options.prefix` and `options.labels`, but these are not passed to the function internally.

## To Reproduce

```js
stackdriver.createWriteStream({ resource: '', prefix: 'hi', labels: [...] })
```

## Expected behavior

Should pass prefix and labels to `toLogEntry`. Currently it only passes `resource` and `keys`.

## Workaround

Since all the internal functions are exposed, is possible to do this with custom code:

```ts
import {
  parseJsonStream,
  toLogEntryStream,
  toStackdriverStream,
} from 'pino-stackdriver/src/stackdriver.js'
import Pumpify from 'pumpify'

declare type PinoStreamOptions = {
  projectId: string
  credentials?: string
  prefix?: string
  logName?: string
  resource?: string
  keys?: {
    httpRequest?: string
    trace?: string
  }
}

const createWriteStream = (options: PinoStreamOptions) =>
  new Pumpify(
    parseJsonStream(),
    toLogEntryStream(options),
    toStackdriverStream(options)
  )
```

However, it's a pain to make it work with TypeScript due to the lack of types of the internal functions.

**Comment by ovhemert** [comment]
Would be great if you can send me a PR to fix the issue that you found.
