### ISSUE TITLE
Fix pino-multi-stream API example

### ISSUE THREAD

**Issue by ai** [ovhemert/pino-stackdriver#70]
## 🐛 Bug Report

[The main guide](https://github.com/ovhemert/pino-stackdriver/blob/master/docs/API.md) does not work.

## To Reproduce

```js
const writeStream = stackdriver.createWriteStream({ credentials, projectId })
const logger = pinoms({ streams: [writeStream] })
```

## Expected behavior

I got an error from TypeScript:

```js
$ tsc --build tsconfig.json 
index.ts:53:53 - error TS2741: Property 'stream' is missing in type 'WritableStream' but required in type '{ stream: WritableStream | DestinationStream; level?: "error" | "debug" | "fatal" | "warn" | "info" | "trace" | undefined; }'.

53     const logger = pinoms({ streams: [writeStream] })
```

## Your Environment

- *os*: Linux
- *pino-stackdriver*: 2.1.0

**Comment by ovhemert** [comment]
Does the problem occur only with pino multi stream v5.x?
It's currently not tested, and due to major version bump, I expect that some types would be incompatible.

**Comment by ai** [comment]
Yeap.

**Comment by slhck** [comment]
Shouldn't this simply be?

```
pinoms({ streams: [{ stream: writeStream }] })
```
