### ISSUE TITLE
Errors in remote API are not shown

### ISSUE THREAD

**Issue by slhck** [ovhemert/pino-stackdriver#74]
## 🐛 Bug Report

When the CLI program hits a 404 response from the Google Cloud API, it does not show any error, just says "logging".

## To Reproduce

Try to log with the CLI program to a non-existing project ID.

```
$ ./my-program | pino-stackdriver --project bar --credentials foo.json
logging
```

In the Google Cloud Console I see the corresponding errors in the logging API:

![image](https://user-images.githubusercontent.com/582444/90106407-a7737680-dd47-11ea-84dc-8121a0236225.png)

However, `pino-stackdriver` does not tell me about those.

## Expected behavior

The CLI program should inform me about the remote API errors so that they can be fixed.

## Your Environment

- *os*: Ubuntu 20.04

**Comment by slhck** [comment]
I would still consider this an open issue.

**Comment by ovhemert** [comment]
Closing the issue,.. will not change this atm since it breaks existing functionality.
Need to keep the process running regardless of any errors that occur.

**Comment by slhck** [comment]
The process can stay running but it should at least show the errors.

**Comment by slhck** [comment]
Could you please consider reopening this issue? I believe that it's vital to inform the user of upstream errors, and the reason you gave for closing doesn't even apply. The program should of course stay running. I never asked for completely different behavior.

I am also willing to provide a PR for this if you agree that this would be useful.
