### ISSUE TITLE
i can`t see release 2.1.1 changes when install with npm

### ISSUE THREAD

**Issue by jhonny111s** [ovhemert/pino-stackdriver#92]
Before you submit an issue we recommend you first check if an existing issue does not already exist.

**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed.**

## 🐛 Bug Report

I am trying to use the credentials as an object, which was added in the new release and the functionality does not appear, installing the package from npm version 2.1.1 

## To Reproduce

- install package 
- check the CLI documentation, it is incomplete or does not correspond to the last commit 

```js
npm i pino-stackdriver
```

## Expected behavior

be able to use the latest version with the latest changes shown on github 

## Your Environment

- *os*: Mac

**Comment by ovhemert** [comment]
Can you specify what exactly is missing?

When I use the Explorer-tab on NPM, I can see that the credentials object can be passed-in, so the release is conform the latest.

```
module.exports.createWriteStream = ({
  credentials,
  ...
})
```

**Comment by jhonny111s** [comment]
I  don't have access to explorer tab, but I mean this: 

```
module.exports.createWriteStream = ({
// credential as Object
  credentials: {
    client_email: 'email',
    private_key: 'key'
}
  ...
})
```
