### ISSUE TITLE
It currently waits a log line is uploaded and it does not perform batching but uploads one at a time.

### ISSUE THREAD

**Issue by meotimdihia** [ovhemert/pino-stackdriver#99]
## 🐛 Bug Report
It currently waits a log line is uploaded and it does not perform batching but uploads one at a time.
Reference from the issue: 
https://github.com/pinojs/pino/issues/1064
Currently, it's near impossible to use pino-stackdriver + fastify in the production with this bug. ...

## Your Environment
- *os*: Ubuntu 20.04

**Comment by kibertoad** [comment]
Would you consider sending a PR for this issue, with a test?

**Comment by meotimdihia** [comment]
Sorry, I don't really understand exactly how this works O_O.

**Comment by ovhemert** [comment]
The transport already uses auto batching of log entries using the the Google logging library. Your problem might be that there is a high volume of log messages. I've made a small change that ensures messages will be sent without waiting for the confirmation which improves the batching. See: #102

**Comment by meotimdihia** [comment]
Thanks for the update. 😀

**Comment by mcollina** [comment]
I think we can close this

**Comment by meotimdihia** [comment]
I close the issue.
